/** @type {import('jest').Config} */

module.exports = {
    preset: 'ts-jest',
    testEnvironment: 'node',
    transform: {
        '^.+\\.ts$': [
            'ts-jest',
            {
                tsconfig: '<rootDir>/tsconfig.json',
                isolatedModules: true,
                // astTransformers: {
                //     before: [],
                //     after: [],
                // },
            },
        ],
    },
    setupFiles: ['dotenv/config'],
    moduleFileExtensions: ['js', 'json', 'ts'],
    coverageReporters: ['lcov', 'text', 'json'],
    resetMocks: true,
    clearMocks: true,
    maxWorkers: '25%',
    testTimeout: 30000,
    detectOpenHandles: true,
    testRunner: 'jest-circus/runner',
    passWithNoTests: true,
    moduleDirectories: ['node_modules', 'src'],
    testMatch: ['**/*.spec.ts'],
    coverageDirectory: '../coverage',
    verbose: false,
    haste: {
        forceNodeFilesystemAPI: true,
    },
    coveragePathIgnorePatterns: [
        '/node_modules/',
        '/dist/',
        '/docs/',
        '/constants/',
        '.*-validations\\.ts$',
        '.*mock\\.ts$',
        '.*-data\\.ts$',
        '.*\\.schema\\.ts$',
        '.*\\.error\\.ts$',
        '.*\\.interface\\.ts$',
        '.*\\.type\\.ts$',
        '.*\\.types\\.ts$',
        '/index\\.ts$',
        '.*\\.module\\.ts$',
        '.*\\.spec\\.ts$',
        '.*\\.enum\\.ts$',
        '.*\\.dto\\.ts$',
        '/main\\.ts$',
        '.*constants\\.ts$',
        '.*\\.constant\\.ts$',
        '.*\\.constants\\.ts$',
        '/test\\.config\\.ts$',
        '/schema-validator\\.ts',
        '/exceptions/',
        '/decorators/',
        '/dbops/',
        '/default-configuration/',
    ],
};
