export enum ErrorCode {
    // General/Common Errors
    PARTIAL_CHANGE = 'PARTIAL_CHANGE',
    INVALID_INPUT = 'INVALID_INPUT',
    THIRDPARTY_SERVICE_ERROR = 'THIRDPARTY_SERVICE_ERROR',
    DATABASE_ERROR = 'DATABASE_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
    AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR',
}
